
    # can't use commands because we need redirection, piping or wildcards. so use shell instead



    - apt: name=dh-autoreconf
    - apt: name=alien

    - git: repo=https://github.com/zfsonlinux/spl.git dest=/root/spl version=spl-0.6.5-release
    - command: ./autogen.sh chdir=/root/spl creates=configure
    - command: ./configure chdir=/root/spl creates=Makefile
    - shell: make deb-utils deb-kmod && touch ansible-compiled chdir=/root/spl creates=ansible-compiled
    - shell: dpkg -i *.deb && touch ansible-installed chdir=/root/spl creates=ansible-installed


    - apt: name=uuid-dev
    - git: repo=https://github.com/zfsonlinux/zfs.git dest=/root/zfs version=zfs-0.6.5-release
    - command: ./autogen.sh chdir=/root/zfs creates=configure
    - command: ./configure chdir=/root/zfs creates=Makefile
    - shell: make deb-utils deb-kmod && touch ansible-compiled chdir=/root/zfs creates=ansible-compiled
    - shell: dpkg -i *.deb && touch ansible-installed chdir=/root/zfs creates=ansible-installed

    - modprobe: name=zfs state=present

    - template: src=mount.j2 dest=/root/mount.sh mode=0755
    - template: src=unmount.j2 dest=/root/unmount.sh mode=0755



# another way
#    - shell: chdir=/root/zfs creates=ansible-done {{item}} 
#      with_items:
#      - ./autogen.sh 
#      - ./configure 
 

