

  # TODO perhaps use web3.js for building cpp-ethereum
  - shell: npm install web3

  # this isn't node specific
  - file: path=/root/examples state=directory
  - copy: src=last_block.js dest=/root/examples
  - copy: src=token.js dest=/root/examples
  - copy: src=token.solc dest=/root/examples



