
  # TODO chdir should be relative path, so can build under other accounts

  # Go
  # install to /usr/local/go since it's the default for GOROOT
  - get_url: |
      url=https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz
      dest=./go1.4.2.linux-amd64.tar.gz
  - unarchive: src=/root/go1.4.2.linux-amd64.tar.gz dest=/usr/local copy=no
  - file: src=/usr/local/go/bin/go dest=/usr/local/bin/go state=link


  # Geth
  # April 10, main branch master, with tags
  - debug: msg="building geth"
  - apt: name=make
  - apt: name=gcc
  - apt: name=libgmp-dev
  - git: repo=https://github.com/ethereum/go-ethereum dest=/root/go-ethereum version=v1.3.6
  - shell: make creates=build/bin/geth chdir=/root/go-ethereum


  - file: src=/root/go-ethereum/build/bin/geth dest=/usr/local/bin/geth state=link
