- hosts: 131.217.38.36

  pre_tasks:
    - command: echo my pretask

  roles:
    - yaegashi.blockinfile
    - { role: distribution, template: debian.j2, version: testing, upgrade: safe, mirror: "http://mirror.aarnet.edu.au/debian" }
    # - ansible-oracle-java  

    - ansible-oracle-java  

  sudo: no
  vars: 
    - common: ./roles/common

    - java_version: 7
    - java_subversion: 80
    - java_download_path: /home/meteo/imos/myjava
    # actually gets installed to /usr/java/default which is horrible 
    - java_remove_download: false

  tasks:
    # hostname?


    # - role: zfs
    - include: "{{common}}/tasks/sudoers.yml"
    - include: "{{common}}/tasks/disable-shell-bell.yml"
    - include: "{{common}}/tasks/bridge.yml"

    - user: name=meteo shell=/bin/bash groups=adm append=yes
    - include: "{{common}}/tasks/mydotfiles.yml user=meteo" 

    - include: "{{common}}/tasks/chefdk.yml"
    - include: "{{common}}/tasks/grails-1.3.7.yml"

    - lineinfile: dest=/home/meteo/paths state=present insertafter=EOF line='export JAVA_HOME=/usr/java/jdk1.7.0_80'

    - apt: name=memtest86
    - apt: name=fail2ban

    - apt: name=alsa-oss
    - apt: name=alsa-utils
    - apt: name=alsa-tools

    - name: Setup soundcard
      blockinfile:
        dest: /etc/modprobe.d/alsa-base.conf
        create: true
        content: |
          # hdmi and cth reversed
          options snd_hda_intel enable=0,1

          # hardware beep off
          options snd_hda_intel beep_mode=0
          blacklist pcspkr
      notify: reboot

    - name: Initialize alsa
      # command: bash -c "/usr/sbin/alsactl"
      command: /usr/sbin/alsactl
      args:
        creates: /var/lib/alsa/asound.state
      notify: reboot

    - name: Wifi firmware
      apt: name=firmware-iwlwifi

    - name: Modprobe
      modprobe: name=iwlwifi state=present

    - name: Bring up interface
      command: /sbin/ifconfig wlp2s0 up

    - apt: name=wpasupplicant
    - apt: name=wicd-curses


    # make sure systemd is installed
    - apt: name=systemd-container
      when: (ansible_distribution == "Debian" and ansible_distribution_major_version > "8")

    - apt: name=debootstrap

    # TODO add devenv and desktop...


  handlers:
    - include: "{{common}}/handlers/main.yml"

