# container instance, using dhcp
# TODO change name to geonetwork

---
- hosts: all
  vars:
    - sshkey: "{{ lookup('file', '/home/meteo/.ssh/id_rsa.pub') }}"

  tasks:
    - user: name=meteo shell=/bin/bash groups=adm append=yes
    - include: ./roles/common/tasks/mydotfiles.yml user=meteo
    - authorized_key: user=meteo key="{{sshkey}}"

    - include: ./roles/common/tasks/sudoers.yml
    - include: ./roles/common/tasks/devenv.yml

    - include: ./roles/distribution/tasks/main.yml template=debian.j2 version=jessie upgrade=safe mirror="http://mirror.aarnet.edu.au/debian"
    - include: ./roles/geonetwork/tasks/main.yml



