# container instance, using dhcp
# TODO change name to geonetwork

---
- hosts: all

  roles:
    - { role: distribution, template_src: debian-sources.j2, version: jessie, upgrade_type: safe, mirror: "http://mirror.aarnet.edu.au/debian" } # "
    - oracle-java
    - geonetwork
    
  tasks:
    - authorized_key: user=meteo key="{{ lookup('file', '/home/meteo/.ssh/id_rsa.pub') }}" # "
    - include: roles/common/tasks/devenv.yml
    - include: roles/common/tasks/user.yml user=meteo
 
