# container instance, using dhcp
# TODO change name to geonetwork

---
- hosts: all
  vars: 
    - sshkey: "{{ lookup('file', '/home/meteo/.ssh/id_rsa.pub') }}"
    - common: ./roles/common/tasks
  roles:
    - { role: distribution, template_src: debian-sources.j2, version: jessie, upgrade_type: safe, mirror: "http://mirror.aarnet.edu.au/debian" } # "
    - oracle-java
    - geonetwork
    
  tasks:
    - include: "{{common}}/sudoers.yml"
    - include: "{{common}}/user.yml user=meteo"
    - include: "{{common}}/devenv.yml"
    - authorized_key: user=meteo key="{{sshkey}}"

    - apt: name=postgresql-9.4-postgis-2.1
 
