
  # template first, in case original mirror is down.
  # - template: src=debian.j2 dest=/etc/apt/sources.list mode=0644

  # set up sources first, in case default mirror is down
  - copy:
      dest: /etc/apt/sources.list
      backup: yes
      mode: 0644
      content: |
        # deployed by ansible
        deb {{mirror}} {{version}} main
        deb-src {{mirror}} {{version}} main

        deb http://security.debian.org/ {{version}}/updates main
        deb-src http://security.debian.org/ {{version}}/updates main

        deb {{mirror}} {{version}}-updates main
        deb-src {{mirror}} {{version}}-updates main

        # firmware
        # deb http://http.us.debian.org/debian/ {{version}} non-free contrib
        deb {{mirror}} {{version}} non-free contrib


  # ansible requires aptitude to be installed in order to perform upgrade!
  - apt: name=aptitude update_cache=yes

  - apt: state=latest update_cache=yes upgrade={{upgrade}}

  # https://realguess.net/2014/12/21/ansible-update-servers-to-the-latest-and-reboot/
  # http://docs.ansible.com/ansible/playbooks_conditionals.html
  - name: Check reboot is required
    register: file
    stat: path=/var/run/reboot-required get_md5=no

  # reboot before continuing - not in a handler
  - name: Reboot the server
    command: /sbin/reboot
    when: file.stat.exists == true



