
  - set_fact: user=meteo


  - set_fact:
      home_dir: /home/{{ user }}
    when: "not \"{{ user }}\" == \"root\""

  - set_fact:
      home_dir: /root
    when: "\"{{ user }}\" == \"root\""

  - apt: name=git

  - git: >
      repo=http://github.com/julian1/dotfiles.git
      dest="{{home_dir}}/dotfiles"
      version=master
      force=yes
    become: true
    become_user: "{{user}}"
    register: git_repository

  - shell: ./install.sh
    become: true
    become_user: "{{user}}"
    args:
      chdir: "{{home_dir}}/dotfiles"
    when: git_repository.changed == true

