
  - set_fact: user=meteo

  - apt: name=git

  - git: >
      repo=http://github.com/julian1/dotfiles.git
      dest=/home/{{user}}/dotfiles
      version=master
      force=yes
    become: true
    become_user: "{{user}}"
    register: git_repository

  - shell: ./install.sh
    become: true
    become_user: "{{user}}"
    args:
      chdir: /home/{{user}}/dotfiles/
    when: git_repository.changed == true

