
- hosts: aatams
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
    - user: meteo
  vars_files:
    - credentials.yml

  roles:
    - yaegashi.blockinfile
    - debian
    - timezone
    - locale
    - basic
    - tomcat-port-forwarding
    - postgres

  tasks:
    #- include: ../roles/aatams/tasks/main.yml

  handlers:
    - include: ../roles/common/handlers/main.yml

