
- hosts: aatams
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
  vars_files:
    - credentials.yml
  roles:
    # should specify yaegashi as dependency for roles, where it's actually used...
    - yaegashi.blockinfile
    - debian
    - timezone
    - locale
    - meteo
    - tomcat-port-forwarding
    - postgres

  tasks:
    #- include: ../roles/aatams/tasks/main.yml

  handlers:
    - include: ../roles/common/handlers/main.yml

