
- hosts: apache
  vars:
    - user: meteo
    - timezone: Australia/Hobart
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
  vars_files:
    - credentials.yml   # needed for meteo ssh key,
                        # TODO split out local keys into a seperate file or else specify explicitly...
  roles:
    - yaegashi.blockinfile
    - debian
    - basic
  tasks:
    # - include: ../roles/common/tasks/basic.yml
    # apache
    - apt: name=apache2

    # mod proxy
    - apt: name=libapache2-mod-proxy-html

    # TODO this is not idempotent
    # enable proxy
    - command: a2enmod proxy proxy_http
    - command: a2enmod proxy proxy_html

    # TODO ordering,
    # disable default site
    - command: a2dissite 000-default.conf

    # reverse proxy
    - blockinfile:
        dest: /etc/apache2/sites-available/default.conf
        create: true
        content: |
          <VirtualHost *:80>

            # DocumentRoot      /aatams
            # Require all granted
            ProxyPass         /aatams http://aatams:8080/aatams
            ProxyPassReverse  /aatams http://aatams:8080/aatams

            ProxyPass         /portal http://portal:8080/portal
            ProxyPassReverse  /portal http://portal:8080/portal

            ProxyPass         /geonetwork http://geonetwork2:8080/geonetwork
            ProxyPassReverse  /geonetwork http://geonetwork2:8080/geonetwork

            ProxyPass         /geoserver http://geoserver:8080/geoserver
            ProxyPassReverse  /geoserver http://geoserver:8080/geoserver

            # Rewriting URLs in hyperlinks
            # ProxyHTMLEnable On
            # ProxyHTMLExtended On
            # ProxyHTMLURLMap http://apache/geonetwork2  /geonetwork
          </VirtualHost>
      notify: reload-apache2

    # enable
    - command: a2ensite default

  handlers:
    - include: ../roles/common/handlers/main.yml


