# TODO hide the passphrase
# it's easiest to use direct wired interface eth1, 172.16.210.254 to provision

- hosts: 192.168.42.1
  roles:
    - yaegashi.blockinfile
  vars:
    - user: meteo
    - sshkey: "{{ lookup('file', '../resources/keys') }}"
  tasks:
    - include: ../roles/distribution/tasks/main.yml template=debian.j2 version=jessie upgrade=safe mirror="http://mirror.aarnet.edu.au/debian"
    - hostname: name=apu

    - include: ../roles/common/tasks/timezone.yml timezone=Australia/Tasmania

    - apt: name=locales
    - locale_gen: name=en_AU.UTF-8 state=present

    - include: ../roles/common/tasks/sudoers.yml

    - user: name="{{user}}" shell=/bin/bash groups=adm append=yes
    - authorized_key: user="{{user}}" key="{{sshkey}}"

    - include: ../roles/common/tasks/mydotfiles.yml user=meteo

    - apt: name=vim
    - apt: name=ntp
    - apt: name=tcpdump
    # - apt: name=fail2ban # not if there's no open ssh, since complicates iptables rules

    # iwconfig - useful to check wlan0 state
    - apt: name=wireless-tools

    # Atheros AR9280 and wlan0 should be seen and can do iwlist scan
    - apt: name=firmware-realtek

    # ip forwarding
    - lineinfile: dest=/etc/sysctl.conf backup=true state=present regexp='.*net.ipv4.ip_forward.*' line='net.ipv4.ip_forward = 1'
      notify: reload-sysctl

    - apt: name=hostapd

    # put hostapd first because the file is referred to
    - blockinfile:
        dest: /etc/hostapd/hostapd.conf
        create: true
        content: |
          interface=wlan0
          ssid=My_AP3
          hw_mode=g
          channel=7
          auth_algs=1
          wmm_enabled=0
          # The following gives us wpa2
          macaddr_acl=0
          ignore_broadcast_ssid=0
          wpa=2
          # TODO hide this!!!
          wpa_passphrase=____apple____
          wpa_key_mgmt=WPA-PSK
          wpa_pairwise=TKIP
          rsn_pairwise=CCMP
      notify: restart-hostapd

      # TODO issue for first run, is that we want a clear network interfaces
      # but we need the network up to be able to run ansible

    - blockinfile:
        dest: /etc/network/interfaces
        backup: yes
        content: |
          # loopback
          auto lo
          iface lo inet loopback

          # wan
          allow-hotplug eth0
          iface eth0 inet dhcp

          # static
          auto eth1
          iface eth1 inet static
            address 172.16.210.254
            netmask 255.255.255.0

          # lan
          auto eth2
          iface eth2 inet static
            address 192.168.43.1
            netmask 255.255.255.0

          # wireless lan
          auto wlan0
          iface wlan0 inet static
            hostapd /etc/hostapd/hostapd.conf
            address 192.168.42.1
            netmask 255.255.255.0

      notify:
        # will these all be run together
        - restart-eth0
        - restart-eth1
        - restart-eth2
        - restart-wlan0

    - apt: name=dnsmasq
    - blockinfile:
        dest: /etc/dnsmasq.d/wifi
        create: true
        content: |
          interface=wlan0
          dhcp-range=192.168.42.10,192.168.42.20,255.255.255.0,12h
          dhcp-ignore-names

          address=/apu/192.168.42.1
          dhcp-host=f8:16:54:1c:9e:90,dell-home,192.168.42.14

          log-queries
          log-dhcp
      notify: restart-dnsmasq

    - blockinfile:
        dest: /etc/dnsmasq.d/lan
        create: true
        content: |
          interface=eth2
          dhcp-range=192.168.43.10,192.168.43.20,255.255.255.0,12h
          dhcp-ignore-names

          address=/apu/192.168.43.1
          dhcp-host=78:a0:51:5c:75:53,budii,192.168.43.10 
          dhcp-host=ac:9b:0a:91:6c:37,bravia,192.168.43.16

          log-queries
          log-dhcp
      notify: restart-dnsmasq

      # may need to restart wlan0 here? at least when install dnsmasq
    - apt: name=iptables-persistent

    - blockinfile:
        dest: /etc/iptables-rules
        create: true
        content: |
          #################
          # FILTER INPUT RULES
          # TODO - should this be here, will interfere with fail2ban
          iptables --flush INPUT -t filter
          # input default policy
          iptables -P INPUT DROP
          # test interface listening on eth0
          iptables -I INPUT 1 -p tcp --dport 82 -j ACCEPT
          # incoming lan ssh regardless of state
          iptables -I INPUT 1 ! -i eth0 -p tcp --dport 22 -j ACCEPT
          # incoming http to enable apt-get update/upgrade 
          # TODO, should only be state established,related
          iptables -I INPUT 1 -p tcp --sport 80 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 443 -j ACCEPT
          # dnsmasq
          # incomming dns requests from lan to dnsmasq service
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 53 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0 -p tcp --dport 53 -j ACCEPT
          # and dns request responses coming back from external servers
          # TODO should be conntrack established, related. 
          iptables -I INPUT 1 -p udp --sport 53 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 53 -j ACCEPT
          # dhcp coming in from lan
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 67 -j ACCEPT
          # dlna from lan
          iptables -I INPUT 1 ! -i eth0 -p tcp --dport 8200 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 1900 -j ACCEPT

          #################
          # NAT PREROUTING RULES
          iptables --flush PREROUTING -t nat 
          # http://serverfault.com/questions/594835/what-is-the-correct-way-to-open-a-range-of-ports-in-iptables
          # Good voip guide, note the comment to limit stp to smaller port range
          # http://whirlpool.net.au/wiki/iiNetPhone_asterisk
          # udp or tcp
          iptables -t nat -A PREROUTING -p udp --match multiport --dport 5060 -i eth0 -j DNAT --to 192.168.43.10
          iptables -t nat -A PREROUTING -p tcp --match multiport --dport 5060 -i eth0 -j DNAT --to 192.168.43.10

          iptables -t nat -A PREROUTING -p udp --match multiport --dport 15000:49999 -i eth0 -j DNAT --to 192.168.43.10

          #################
          # NAT POSTROUTING RULES
          # TODO remove the ! -d rules, which shouldn't be needed with -o
          iptables --flush POSTROUTING -t nat 
          iptables -t nat -A POSTROUTING -s 192.168.42.0/24 ! -d 192.168.42.0/24 -o eth0 -j MASQUERADE
          iptables -t nat -A POSTROUTING -s 192.168.43.0/24 ! -d 192.168.43.0/24 -o eth0 -j MASQUERADE

      notify: reconfigure-iptables

    # - apt: name=minidlna

    # multicast subnet routing for minidlna udp on 1900
    # Use, ip -s mroute to query status
    - apt: name=smcroute

    - blockinfile:
        dest: /etc/smcroute/startup.sh
        mode: 0755
        create: true
        content: |
          sleep 1
          smcroute -a wlan0 0.0.0.0 239.255.255.250 eth2
          smcroute -a eth2  0.0.0.0 239.255.255.250 wlan0
          # smcroute -a wlan1 192.168.42.14 239.255.255.250 eth2
      notify: restart-smcroute


  handlers:
    - include: ../roles/common/handlers/main.yml


