
# apu router with wireless ap, vlan trunking, dns/dhcp, multicast-routing, voip, nat, tftp, xmodem serial

# TODO hide hostap passphrase

- hosts: 192.168.42.1
  tasks:
    - include: >
        ../roles/distribution/tasks/main.yml
        mirror=http://mirror.internode.on.net/pub/debian
        template=debian.j2
        version=testing
        upgrade=safe

    - hostname: name=apu

    - lineinfile: >
        dest=/etc/hosts
        state=present
        line='127.0.1.1       apu'

    - include: ../roles/common/tasks/basic.yml

    - apt: name=ntp             # network time
    - apt: name=tcpdump
    - apt: name=netstat-nat     # nat connections
    - apt: name=dnsutils        # dig, whois
    - apt: name=wireless-tools  # iwconfig - useful to check wlan0 state
    - apt: name=pciutils        # lspci
    - apt: name=usbutils        # lsusb

    # sensors
    - apt: name=lm-sensors
    - shell: creates=ansible-lm-sensors {{item}}
      with_items:
        - sensors-detect --auto
        - touch ansible-lm-sensors

    # Atheros AR9280 and wlan0 should be seen and can do iwlist scan
    - apt: name=firmware-realtek

    # ip forwarding
    - lineinfile: >
        dest=/etc/sysctl.conf
        state=present
        regexp='.*net.ipv4.ip_forward.*'
        line='net.ipv4.ip_forward = 1'
      notify: reload-sysctl

    - apt: name=hostapd

    # hostapd.conf goes first since referred to by /etc/network/interfaces
    - copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
          # deployed by ansible!
          interface=wlan0
          ssid=My_AP3
          hw_mode=g
          channel=7
          auth_algs=1
          wmm_enabled=0
          # The following gives us wpa2
          macaddr_acl=0
          ignore_broadcast_ssid=0
          wpa=2
          # TODO hide this!!!
          wpa_passphrase=____apple____
          wpa_key_mgmt=WPA-PSK
          wpa_pairwise=TKIP
          rsn_pairwise=CCMP
      notify: restart-hostapd

    - copy:
        dest: /etc/network/interfaces
        content: |
          # deployed by ansible!
          # loopback
          auto lo
          iface lo inet loopback

          # wan
          # allow-hotplug eth0
          #   iface eth0 inet dhcp

          # http://www.cyberciti.biz/tips/howto-configure-linux-virtual-local-area-network-vlan.html
          # just had to do /sbin/ifup eth0.100.100
          # VLAN = Third octet of IPv4 subnets, network identifier in IPv6 addresses.
          # make 100 -> management, make 120 -> wlan.  move

          # vlan100, switch management
          auto eth0.100
          iface eth0.100 inet static
            address 192.168.100.1
            netmask 255.255.255.0
            vlan-raw-device eth0

          # vlan120, wan on dhcp
          auto eth0.120
          iface eth0.120 inet dhcp
            vlan-raw-device eth0

          # vlan200, lan2
          auto eth0.200
          iface eth0.200 inet static
            address 192.168.200.1
            netmask 255.255.255.0
            vlan-raw-device eth0

          # router management
          # TODO do we need allow-hotplug?
          auto eth1
          iface eth1 inet static
            address 172.16.1.1
            netmask 255.255.255.0

          # lan1 is 42 on eth2
          auto eth2
          iface eth2 inet static
            address 192.168.42.1
            netmask 255.255.255.0

          # wireless-lan on wlan0
          auto wlan0
          iface wlan0 inet static
            hostapd /etc/hostapd/hostapd.conf
            address 192.168.43.1
            netmask 255.255.255.0
            # gateway to 10.0.0.0 via dell-home
            # TODO A cleaner way to persist routing entries?
            post-up ip route add 10.0.0.0/8 via 192.168.43.14

      notify:
        # will these all be run together
        # TODO - restart networking generally?
        # TODO restart-eth0.100 and 200
        - restart-eth1
        - restart-eth2
        - restart-wlan0

    - apt: name=dnsmasq

    - copy:
        # TODO change this filename!
        dest: /etc/dnsmasq.d/wifi
        content: |
          # deployed by ansible!
          # https://wiki.debian.org/HowTo/dnsmasq
          dhcp-ignore-names
          # will expand dhcp entries. not address entries (eg. apu)
          expand-hosts
          domain=localnet
          # log-queries
          # dhcp-ignore-names
          log-dhcp

          # lan1
          interface=eth2
          dhcp-range=eth2,192.168.42.10,192.168.42.20,255.255.255.0,12h
          dhcp-host=78:a0:51:5c:75:53,budii,192.168.42.10
          dhcp-host=ac:9b:0a:91:6c:37,bravia,192.168.42.16
          dhcp-host=b8:ae:ed:7b:b5:b9,nuc,192.168.42.17
          dhcp-host=08:17:35:34:c9:c0,cisco1000,192.168.42.18
          dhcp-host=00:04:13:37:1a:f1,snom,192.168.42.20
          dhcp-host=b8:2a:72:c9:fe:d2,dell-home-wired,192.168.42.19

          # wireless
          interface=wlan0
          dhcp-range=wlan0,192.168.43.10,192.168.43.20,255.255.255.0,12h
          dhcp-host=f8:16:54:1c:9e:90,dell-home,192.168.43.14
          dhcp-host=00:19:e3:10:53:89,imac,192.168.43.15
          dhcp-host=60:57:18:75:3b:cc,asus,192.168.43.17

          # it doesn't matter which interface ip we use here
          # although wireless is more isolated from rest of switch environment
          # no-hosts is required to avoid returning the 127.0.0.1 entry in /etc/hosts
          no-hosts
          address=/apu/192.168.43.1
          address=/apu.localnet/192.168.43.1

          # vlan100
          # cisco switch has static assignment on vlan100
          # dhcp-host=00:08:30:1e:dd:c0,cisco100,192.168.100.11
          address=/cisco100/192.168.100.11
          address=/cisco100.localnet/192.168.100.11

          # vlan200 is lan2 
          interface=eth0.200
          dhcp-range=eth0.200,192.168.200.10,192.168.200.20,255.255.255.0,12h
          # Note, increased brother dhcp retries to 10 due slow switch startup
          dhcp-host=00:80:77:34:55:96,brother,192.168.200.15

      notify: restart-dnsmasq


      # may need to restart wlan0 here? at least when install dnsmasq
    - apt: name=iptables-persistent

    - copy:
        dest: /etc/iptables-rules
        content: |
          # deployed by ansible!
          #####
          # filter
          iptables -t filter --flush
          iptables -t nat --flush
          iptables -t mangle --flush

          #####
          # input default policy
          iptables -P INPUT DROP

          # Incoming from WAN/eth0.120 (TODO state conntrack established, related in forward)
          # TODO remove the 1
          # http responses - required for apt-get update/upgrade
          iptables -I INPUT 1 -p tcp --sport 80 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 443 -j ACCEPT
          # dns responses
          iptables -I INPUT 1 -p udp --sport 53 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 53 -j ACCEPT
          # ping/icmp responses
          iptables -I INPUT 1 -p icmp -j ACCEPT

          # Internal
          # ssh
          iptables -I INPUT 1 ! -i eth0.120 -p tcp --dport 22 -j ACCEPT
          # tftp - port-range is inclusive
          iptables -I INPUT 1 ! -i eth0.120 -p udp --match multiport --dport 69,1024:1034 -j ACCEPT
          # dns
          iptables -I INPUT 1 ! -i eth0.120 -p udp --dport 53 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0.120 -p tcp --dport 53 -j ACCEPT
          # dhcp
          iptables -I INPUT 1 ! -i eth0.120 -p udp --dport 67 -j ACCEPT
          # dlna
          iptables -I INPUT 1 ! -i eth0.120 -p tcp --dport 8200 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0.120 -p udp --dport 1900 -j ACCEPT

          #####
          # nat
          # pre-routing
          # voip
          # http://serverfault.com/questions/594835/what-is-the-correct-way-to-open-a-range-of-ports-in-iptables
          # Good voip guide, note the comment to limit stp to smaller port range
          # http://whirlpool.net.au/wiki/iiNetPhone_asterisk

          # 15000: # 35000-44999
          # iptables -t nat -A PREROUTING -p udp --match multiport --dport 5060 -i eth0.120 -j DNAT --to 192.168.42.20
          # iptables -t nat -A PREROUTING -p tcp --match multiport --dport 5060 -i eth0.120 -j DNAT --to 192.168.42.20
          # iptables -t nat -A PREROUTING -p udp --match multiport --dport 15000:49999 -i eth0.120 -j DNAT --to 192.168.42.20

          # with nat punch-through it's not clear we even need all this
          # or at least tcp on 5060?
          # port forward may even confuse
          iptables -t nat -A PREROUTING -p udp -s 203.55.231.0/24 -i eth0.120 -j DNAT --to 192.168.42.20
          iptables -t nat -A PREROUTING -p tcp -s 203.55.231.0/24 -i eth0.120 -j DNAT --to 192.168.42.20

          # post-routing
          # private subnet nat
          iptables -t nat -A POSTROUTING -s 10.0.0.0/8     -o eth0.120 -j MASQUERADE
          iptables -t nat -A POSTROUTING -s 172.16.0.0/12  -o eth0.120 -j MASQUERADE
          iptables -t nat -A POSTROUTING -s 192.168.0.0/16 -o eth0.120 -j MASQUERADE

          #####
          # mangle

      notify: reconfigure-iptables


    # multicast subnet routing. for example minidlna udp on 1900
    # Use, ip -s mroute to query status
    - apt: name=smcroute
    - copy:
        dest: /etc/smcroute/startup.sh
        mode: 0755
        content: |
          # deployed by ansible!
          sleep 1
          smcroute -a wlan0 0.0.0.0 239.255.255.250 eth2
          smcroute -a eth2  0.0.0.0 239.255.255.250 wlan0
      notify: restart-smcroute


    - apt: name=tftp
    - copy:
        dest: /etc/default/tftpd-hpa
        mode: 0644
        content: |
          # deployed by ansible!
          TFTP_USERNAME="tftp"
          TFTP_DIRECTORY="/srv/tftp"
          TFTP_ADDRESS="0.0.0.0:69"
          TFTP_OPTIONS="--secure --port-range 1024:1034"
      notify: restart-tftpd-hpa

      # /srv/tftp cannot just be owned by tftp. instead must have global read permissions
      # chown -R root:root /srv/tftp
      # chmod 755 $( find /srv/tftp -type d )
      # chmod 644 $( find /srv/tftp -type f )


    # xmodem protocol support over serial for switch firmware
    - apt: name=lrzsz

  handlers:
    - include: ../roles/common/handlers/main.yml


