
# TODO hide hostap passphrase

- hosts: 192.168.42.1
  tasks:
    - include: >
        ../roles/distribution/tasks/main.yml
        mirror=http://mirror.internode.on.net/pub/debian
        template=debian.j2
        version=testing
        upgrade=safe

    - hostname: name=apu

    - lineinfile: >
        dest=/etc/hosts state=present
        line='127.0.1.1       apu'

    - include: ../roles/common/tasks/basic.yml

    - apt: name=vim

    - apt: name=ntp             # network time
    - apt: name=tcpdump
    - apt: name=netstat-nat     # nat connections
    - apt: name=dnsutils        # dig, whois
    - apt: name=wireless-tools  # iwconfig - useful to check wlan0 state

    # sensors
    - apt: name=lm-sensors
    - shell: creates=ansible-lm-sensors {{item}}
      with_items:
        - sensors-detect --auto
        - touch ansible-lm-sensors

    # Atheros AR9280 and wlan0 should be seen and can do iwlist scan
    - apt: name=firmware-realtek

    # ip forwarding
    - lineinfile: > 
        dest=/etc/sysctl.conf 
        state=present 
        regexp='.*net.ipv4.ip_forward.*' 
        line='net.ipv4.ip_forward = 1'
      notify: reload-sysctl

    - apt: name=hostapd

    # put hostapd.conf first since referred to in /etc/network/interfaces
    - copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
          # deployed by ansible!
          interface=wlan0
          ssid=My_AP3
          hw_mode=g
          channel=7
          auth_algs=1
          wmm_enabled=0
          # The following gives us wpa2
          macaddr_acl=0
          ignore_broadcast_ssid=0
          wpa=2
          # TODO hide this!!!
          wpa_passphrase=____apple____
          wpa_key_mgmt=WPA-PSK
          wpa_pairwise=TKIP
          rsn_pairwise=CCMP
      notify: restart-hostapd

    - copy:
        dest: /etc/network/interfaces
        content: |
          # deployed by ansible!
          # loopback
          auto lo
          iface lo inet loopback

          # wan
          allow-hotplug eth0
          iface eth0 inet dhcp

          # TODO do we need to enable hotplug?
          # admin
          auto eth1
          iface eth1 inet static
            address 172.16.1.1
            netmask 255.255.255.0

          # wired-lan
          auto eth2
            iface eth2 inet static
            address 192.168.43.1
            netmask 255.255.255.0

          # wireless-lan
          auto wlan0
          iface wlan0 inet static
            hostapd /etc/hostapd/hostapd.conf
            address 192.168.42.1
            netmask 255.255.255.0
            # TODO A cleaner way to persist this?
            post-up ip route add 10.0.0.0/8 via 192.168.42.14

      notify:
        # will these all be run together
        # TODO - restart networking generally?
        - restart-eth0
        - restart-eth1
        - restart-eth2
        - restart-wlan0

    - apt: name=dnsmasq

    - copy:
        dest: /etc/dnsmasq.d/wifi
        content: |
          # deployed by ansible!
          # https://wiki.debian.org/HowTo/dnsmasq
          dhcp-ignore-names
          # will expand dhcp entries (not apu)
          expand-hosts
          domain=localnet
          # log-queries
          # dhcp-ignore-names
          log-dhcp

          # address=/apu/192.168.42.1  should come from /etc/host
          # address=/apu.localnet/192.168.42.1

          interface=wlan0
          dhcp-range=wlan0,192.168.42.10,192.168.42.20,255.255.255.0,12h
          dhcp-host=f8:16:54:1c:9e:90,dell-home,192.168.42.14
          dhcp-host=00:19:e3:10:53:89,imac,192.168.42.15
          dhcp-host=60:57:18:75:3b:cc,asus,192.168.42.17

          interface=eth2
          dhcp-range=eth2,192.168.43.10,192.168.43.20,255.255.255.0,12h
          dhcp-host=78:a0:51:5c:75:53,budii,192.168.43.10
          dhcp-host=00:80:77:34:55:96,brother,192.168.43.15
          dhcp-host=ac:9b:0a:91:6c:37,bravia,192.168.43.16
          dhcp-host=b8:ae:ed:7b:b5:b9,nuc,192.168.43.17
          dhcp-host=08:17:35:34:c9:c0,cisco,192.168.43.18
          dhcp-host=00:04:13:37:1a:f1,snom,192.168.43.20
          dhcp-host=b8:2a:72:c9:fe:d2,dell-home-wired,192.168.43.19

      notify: restart-dnsmasq

      # may need to restart wlan0 here? at least when install dnsmasq
    - apt: name=iptables-persistent

    - copy:
        dest: /etc/iptables-rules
        content: |
          #################
          # filter
          iptables -t filter --flush
          # input default policy
          iptables -P INPUT DROP

          # Incoming from WAN/eth0 (TODO state conntrack established, related).
          # TODO remove the 1
          # http responses from outside (needed for apt-get update/upgrade)
          iptables -I INPUT 1 -p tcp --sport 80 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 443 -j ACCEPT
          # dns responses from outside
          iptables -I INPUT 1 -p udp --sport 53 -j ACCEPT
          iptables -I INPUT 1 -p tcp --sport 53 -j ACCEPT
          # ping/icmp
          iptables -I INPUT 1 -p icmp -j ACCEPT

          # voip 35000-44999
          # iptables -I INPUT 1 -p udp --match multiport --dport 35000:49999 -j ACCEPT

          # Internal traffic
          # incoming test port
          # iptables -I INPUT 1 -p tcp --dport 82 -j ACCEPT
          # ssh
          iptables -I INPUT 1 ! -i eth0 -p tcp --dport 22 -j ACCEPT
          # tftp - /etc/default/tftpd-hpa, TFTP_OPTIONS="--secure  --port-range 1024:1025"
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 69 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 1024 -j ACCEPT
          # dns
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 53 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0 -p tcp --dport 53 -j ACCEPT
          # dhcp
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 67 -j ACCEPT
          # dlna
          iptables -I INPUT 1 ! -i eth0 -p tcp --dport 8200 -j ACCEPT
          iptables -I INPUT 1 ! -i eth0 -p udp --dport 1900 -j ACCEPT

          #################
          # nat
          iptables -t nat --flush

          # pre-routing
          # voip
          # http://serverfault.com/questions/594835/what-is-the-correct-way-to-open-a-range-of-ports-in-iptables
          # Good voip guide, note the comment to limit stp to smaller port range
          # http://whirlpool.net.au/wiki/iiNetPhone_asterisk
          # udp or tcp

          # VERY IMPORTANT - for 15000 we may distinguish from dns using ! port 53 rule. or only redirect if high source port range
          # VERY IMPORTANT  if use apu dns service then it will be non-NAT and won't be affected.

          # 15000: # 35000-44999
          # iptables -t nat -A PREROUTING -p udp --match multiport --dport 5060 -i eth0 -j DNAT --to 192.168.43.20
          # iptables -t nat -A PREROUTING -p tcp --match multiport --dport 5060 -i eth0 -j DNAT --to 192.168.43.20
          # iptables -t nat -A PREROUTING -p udp --match multiport --dport 15000:49999 -i eth0 -j DNAT --to 192.168.43.20

          # with nat punch-through it's not clear we even need all this
          # or at least tcp on 5060?
          # port forward may even confuse
          iptables -t nat -A PREROUTING -p udp -s 203.55.231.0/24 -i eth0 -j DNAT --to 192.168.43.20
          iptables -t nat -A PREROUTING -p tcp -s 203.55.231.0/24 -i eth0 -j DNAT --to 192.168.43.20

          # post-routing
          # private subnet nat
          iptables -t nat -A POSTROUTING -s 10.0.0.0/8     -o eth0 -j MASQUERADE
          iptables -t nat -A POSTROUTING -s 172.16.0.0/12  -o eth0 -j MASQUERADE
          iptables -t nat -A POSTROUTING -s 192.168.0.0/16 -o eth0 -j MASQUERADE

          #################
          # mangle
          iptables -t mangle --flush

      notify: reconfigure-iptables


    # multicast subnet routing. for example minidlna udp on 1900
    # Use, ip -s mroute to query status
    - apt: name=smcroute

    - copy:
        dest: /etc/smcroute/startup.sh
        mode: 0755
        content: |
          sleep 1
          smcroute -a wlan0 0.0.0.0 239.255.255.250 eth2
          smcroute -a eth2  0.0.0.0 239.255.255.250 wlan0
      notify: restart-smcroute


  handlers:
    - include: ../roles/common/handlers/main.yml


