- hosts: chromebox
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: testing
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
    # might be nicer to take from dhcp...
    - hostname: chromebox
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}" }
  vars_files:
    - credentials.yml
  roles:
    - debian
    - timezone
    - locale
    - hostname
    - common
    - meteo-dotfiles
  tasks:
    - apt: name=pciutils        # lspci
    - apt: name=wpasupplicant
    - apt: name=man

