- hosts: dell-home
  vars:
  tasks:
    # TODO change to internode...
    # - include: >
    #    ../roles/distribution/tasks/main.yml
    #    mirror=http://mirror.aarnet.edu.au/debian
    #    template=debian.j2
    #    version=testing
    #    upgrade=safe

    - include: ../roles/common/tasks/basic.yml

    # hostname?

    # zfs playbook must be from /root
    - include: ../roles/common/tasks/disable-shell-bell.yml

    #####
    - apt: name=memtest86

    - apt: name=alsa-oss
    - apt: name=alsa-utils
    - apt: name=alsa-tools

    - copy:
        dest: /etc/modprobe.d/alsa-base.conf
        content: |
          # deployed by ansibl
          # http://darmawan-salihun.blogspot.com.au/2015/02/intel-pch-haswell-sound-alsa-problem.html
          # Intel PCH
          options snd-hda-intel index=0 enable=1 vid=8086 pid=9c20
          # Intel HDMI
          # test using: speaker-test -c 2 -D hdmi:HDMI
          options snd-hda-intel index=1 enable=1 vid=8086 pid=0a0c
          # hardware beep off
          options snd_hda_intel beep_mode=0
          blacklist pcspkr
      notify: reboot

    - name: Initialize alsa
      # command: bash -c "/usr/sbin/alsactl"
      # not sure if this should be with store or init
      command: /usr/sbin/alsactl
      args:
        creates: /var/lib/alsa/asound.state
      notify: reboot

    #####
    - copy:
        dest: /home/meteo/.xinitrc
        content: |
          xrdb -merge <<- EOF
            XTerm*selectToClipboard: true
            XTerm*faceName: DejaVu Sans Mono
            ! XTerm*faceSize: 10 ! desktop
            XTerm*faceSize: 15   ! laptop
            XTerm*Background: white
            XTerm*Foreground: black
          EOF

          xmodmap - <<- EOF
            keycode 90 = Insert NoSymbol Insert
          EOF

          xrandr --output eDP1 --brightness .65

          # xset -dpms; xset s off
          # to turn on trackpad tap to select/button
          synclient TapButton1=1
          xset b off
          # xset q | grep bell
          xmonad

    #####
    # ip forwarding
    - lineinfile: >
        dest=/etc/sysctl.conf
        state=present
        regexp='.*net.ipv4.ip_forward.*'
        line='net.ipv4.ip_forward = 1'
      notify: reload-sysctl

    - apt: name=bridge-utils

    - copy:
        dest: /etc/network/interfaces
        backup: yes
        content: |
          # deployed by ansible
          auto lo
          iface lo inet loopback

          # vlan
          # auto eth0.2
          # iface eth0.2 inet static
          #  address 192.168.2.1
          #  netmask 255.255.255.0

          # auto eth0.3
          # iface eth0.3 inet static
          #  address 192.168.3.1
          #  netmask 255.255.255.0

          auto br0
          iface br0 inet static
            address 10.1.1.1
            netmask 255.255.255.0
            bridge_ports dummy0
            bridge_stp off
            bridge_fd 0

      # probably should restart all networking
      notify: restart-br0

    # Using local dnsmasq as a wholesale replacement for using resolvconf is a lot simpler
    # issue is we want to ping containers from the host,
    # so make local dns authoritative
    - apt: name=dnsmasq
    - copy:
        dest: /etc/dnsmasq.d/container-dns
        content: |
          # deployed by ansible
          interface=br0
          # log-queries
          log-dhcp
          no-resolv
          # server=8.8.8.8
          server=192.168.42.1
          #server=192.168.43.1
          expand-hosts
          domain=container
          dhcp-range=br0,10.1.1.10,10.1.1.20,4h
          dhcp-host=00:01:04:1b:2C:1A,ethereum,10.1.1.19

      notify: restart-dnsmasq

    # IMPORTANT - changes to /etc/resolv.conf, need dnsmasq restart to re-read upstream servers

    # TODO maybe add domain, search?
    - copy:
        dest: /etc/resolv.conf
        content: |
          # deployed by ansible
          # nameserver 127.0.0.1
          nameserver 10.1.1.1

    # http://unix.stackexchange.com/questions/174349/what-overwrites-etc-resolv-conf-on-every-boot
    - copy:
        dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate
        mode: 0777
        content: |
          #!/bin/sh
          # deployed by ansible
          make_resolv_conf() {
              :
          }

    # - lineinfile: dest=/etc/dhcp/dhclient.conf backup=true state=present insertafter='#prepend' line='prepend domain-name-servers 10.1.1.1;'

    # remove domain-name-servers from dhcp config
    # - lineinfile: dest=/etc/dhcp/dhclient.conf backup=true state=present backrefs=yes regexp='(.*)domain-name-servers,(.*)' line='\1\2'

    - apt: name=iptables-persistent
    - copy:
        dest: /etc/iptables-rules
        content: |
          # deployed by ansible
          iptables -t filter --flush
          iptables -t nat --flush
          iptables -t mangle --flush
          # iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
          # iptables -t nat -A PREROUTING -p tcp --dport 80 -i eth0 -j DNAT --to 10.1.1.16
          # iptables -t nat -A POSTROUTING -s '10.1.1.0/24' -j MASQUERADE
          # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717217
          # TODO - fill in checksums for all udp...
          iptables -t mangle -A POSTROUTING -p udp --dport bootpc -j CHECKSUM --checksum-fill

          # FIXME uggh... had to run interactive and select yes to force overwrite of /etc/iptables/rules.v4 ...
          # dpkg-reconfigure iptables-persistent
      notify: reconfigure-iptables

    #####
    # Support bridge addif for qemu
    # tunctl from uml-utilities only needed for permissions, not strictly needed
    - copy:
        dest: /etc/qemu-ifup
        mode: 0755
        content: |
          #!/bin/sh
          # deployed by ansible
          set -x
          switch=br0
          if [ -n "$1" ];then
              # tunctl -u `whoami` -t $1
              ip link set $1 up
              sleep 0.5s
              brctl addif $switch $1
              exit 0
          else
              echo "Error: no interface specified"
              exit 1
          fi

    #####
    # pulled in by .bashrc
    - copy:
        dest: /home/meteo/paths
        content: |
          # deployed by ansible!
          # http://unix.stackexchange.com/questions/30925/in-bash-when-to-alias-when-to-script-and-when-to-write-a-function
          . $HOME/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

          export HISTTIMEFORMAT="%T " # "
          export EDITOR=vim
          # locations
          export H=$HOME
          export A=$HOME/ansible-tests
          export C=$HOME/Config_Stuff2

          alias a="cd $A"
          alias c="cd $C"
          alias dmesg='dmesg -T --color=always'
          alias e='cd /etc'
          alias g='git'
          alias h="cd $HOME"
          # alias hs="history"
          alias less='less -R'
          alias myip='dig +short myip.opendns.com @resolver1.opendns.com'
          alias pong="ping 8.8.8.8 -c 4"
          alias pw='head -c 18 /dev/urandom | base64'
          alias pr='a2ps -1 -R -f 9'
          alias p=ping
          alias s=sudo
          alias t='export T=$(mktemp -d); pushd $T'
          alias top='top -d .7'
          # alias ps='ps auxf'
          alias vim='vim -p'

          function l() {
            ls -lh --group-directories-first --color=always $@ | awk -e '{
              k=0;
              for(i=0;i<=8;i++)
                k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));
                if(k)
                  printf("%0o ",k);
                print
              }'
          }


  handlers:
    - include: ../roles/common/handlers/main.yml

