- hosts: dell-home
  roles:
    - yaegashi.blockinfile
  vars:
  tasks:
    # - include: ../roles/distribution/tasks/main.yml template=debian.j2 version=testing upgrade=safe mirror="http://mirror.aarnet.edu.au/debian"

    - include: ../roles/common/tasks/basic.yml

    # hostname?
    # - role: zfs
    - include: ../roles/common/tasks/disable-shell-bell.yml

    ###################################

    - apt: name=memtest86
    # - apt: name=fail2ban

    - apt: name=alsa-oss
    - apt: name=alsa-utils
    - apt: name=alsa-tools

    - name: Setup soundcard
      blockinfile:
        dest: /etc/modprobe.d/alsa-base.conf
        create: true
        content: |
          # http://darmawan-salihun.blogspot.com.au/2015/02/intel-pch-haswell-sound-alsa-problem.html
          # Intel PCH
          options snd-hda-intel index=0 enable=1 vid=8086 pid=9c20
          # Intel HDMI
          # test using: speaker-test -c 2 -D hdmi:HDMI
          options snd-hda-intel index=1 enable=1 vid=8086 pid=0a0c
          # hardware beep off
          options snd_hda_intel beep_mode=0
          blacklist pcspkr
      notify: reboot

    - name: Initialize alsa
      # command: bash -c "/usr/sbin/alsactl"
      # not sure if this should be with store or init
      command: /usr/sbin/alsactl
      args:
        creates: /var/lib/alsa/asound.state
      notify: reboot

    ###################################

    # ip forwarding needed for nat - debian only?
    - lineinfile: dest=/etc/sysctl.conf backup=true state=present regexp='.*net.ipv4.ip_forward.*' line='net.ipv4.ip_forward = 1'
      notify: reload-sysctl

    - apt: name=bridge-utils
    - blockinfile:
        dest: /etc/network/interfaces
        backup: yes
        content: |
          auto br0
          iface br0 inet static
            address 10.1.1.1
            netmask 255.255.255.0
            bridge_ports dummy0
            bridge_stp off
            bridge_fd 0
      notify: restart-br0

    # Using local dnsmasq as a wholesale replacement for using resolvconf is a lot simpler
    # issue is we want to ping containers from the host,
    # so make local dns authoritative
    - apt: name=dnsmasq
    - blockinfile:
        dest: /etc/dnsmasq.d/container-dns
        create: true
        content: |
          interface=br0
          log-queries
          log-dhcp
          no-resolv
          server=192.168.42.1
          #server=192.168.43.1
          expand-hosts
          domain=container
          dhcp-range=br0,10.1.1.10,10.1.1.20,4h
          dhcp-host=00:01:04:1b:2C:1A,ethereum,10.1.1.19
      notify: restart-dnsmasq

    # TODO - this doesn't clear the file first
    # maybe change nameserver to 127.0.0.1
    # also add domain, search?
    - blockinfile:
        dest: /etc/resolv.conf
        create: true
        content: |
          nameserver 10.1.1.1

    # IMPORTANT for complete files not just blocks, could simply use shell maybe with <<-EOF type stuff

    # http://unix.stackexchange.com/questions/174349/what-overwrites-etc-resolv-conf-on-every-boot
    - blockinfile:
        dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate
        create: true
        mode: 0777
        content: |
          #!/bin/sh
          make_resolv_conf() {
              :
          }

    - apt: name=iptables-persistent
    - blockinfile:
        dest: /etc/iptables-rules
        create: true
        content: |
          # iptables -t nat --flush PREROUTING
          # iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
          # iptables -t nat -A PREROUTING -p tcp --dport 80 -i eth0 -j DNAT --to 10.1.1.16
          # iptables -t nat --flush POSTROUTING
          # iptables -t nat -A POSTROUTING -s '10.1.1.0/24' -j MASQUERADE

          # clear all
          iptables -t filter --flush
          iptables -t nat --flush
          iptables -t mangle --flush
          # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717217
          # TODO - fill in checksums for all udp...
          iptables -t mangle -A POSTROUTING -p udp --dport bootpc -j CHECKSUM --checksum-fill

          # FIXME uggh... had to run interactive and select yes to force overwrite of /etc/iptables/rules.v4 ...
          # dpkg-reconfigure iptables-persistent
      notify: reconfigure-iptables


    # - lineinfile: dest=/etc/dhcp/dhclient.conf backup=true state=present insertafter='#prepend' line='prepend domain-name-servers 10.1.1.1;'

    # remove domain-name-servers from dhcp config
    # - lineinfile: dest=/etc/dhcp/dhclient.conf backup=true state=present backrefs=yes regexp='(.*)domain-name-servers,(.*)' line='\1\2'


  handlers:
    - include: ../roles/common/handlers/main.yml

