
- hosts: dell-home
  vars_files:
    - ../vars/testing.yml
    - ../vars/credentials.yml
  vars:
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}" }
    - printer:
        name: Brother
        url: socket://brother:9100
        ppd: BRHL16_2_GPL.ppd
  roles:
    - debian
    - timezone
    - locale
    - common
    - dotfiles
    - ip-forwarding
    - printer
    - vim

  tasks:
    - hostname: name=dell-home

    - apt: name=memtest86

    - apt: name=wireless-tools  # iwconfig - useful to check wlan1 state
    - apt: name=iw

    #####
    - apt: name=alsa-oss
    - apt: name=alsa-utils
    - apt: name=alsa-tools

    - copy:
        dest: /etc/modprobe.d/alsa-base.conf
        content: |
          # deployed by ansibl
          # http://darmawan-salihun.blogspot.com.au/2015/02/intel-pch-haswell-sound-alsa-problem.html
          # Intel PCH
          options snd-hda-intel index=0 enable=1 vid=8086 pid=9c20
          # Intel HDMI
          # test using: speaker-test -c 2 -D hdmi:HDMI
          options snd-hda-intel index=1 enable=1 vid=8086 pid=0a0c
          # hardware beep off
          options snd_hda_intel beep_mode=0
          blacklist pcspkr
      notify: reboot


    - copy:
        dest: /etc/modprobe.d/zfs.conf
        content: |
          # deployed by ansible!
          # see, http://serverfault.com/questions/581669/why-isnt-the-arc-max-setting-honoured-on-zfs-on-linux
          options zfs zfs_arc_max=34359738368
      notify: reboot



      # command: bash -c "/usr/sbin/alsactl"
      # not sure if this should be with store or init
    - command: /usr/sbin/alsactl
      args:
        creates: /var/lib/alsa/asound.state
      notify: reboot

    #####
    - copy:
        dest: /home/meteo/.xinitrc
        content: |
          xrdb -merge <<- EOF
            XTerm*selectToClipboard: true
            XTerm*faceName: DejaVu Sans Mono
            ! XTerm*faceSize: 10 ! desktop
            XTerm*faceSize: 15   ! laptop
            XTerm*Background: white
            XTerm*Foreground: black
          EOF

          xmodmap - <<- EOF
            keycode 90 = Insert NoSymbol Insert
          EOF

          xrandr --output eDP1 --brightness .45

          # xset -dpms; xset s off
          # to turn on trackpad tap to select/button
          synclient TapButton1=1
          xset b off
          # xset q | grep bell
          xmonad

    #####
    - apt: name=bridge-utils

    - copy:
        dest: /etc/network/interfaces
        backup: yes
        content: |
          # deployed by ansible
          auto lo
          iface lo inet loopback

          auto br0
          iface br0 inet static
            address 10.1.1.1
            netmask 255.255.255.0
            bridge_ports dummy0
            bridge_stp off
            bridge_fd 0

      # probably should restart all networking
      notify: restart-br0

    # Using local dnsmasq as a wholesale replacement for using resolvconf is a lot simpler
    # issue is we want to ping containers from the host,
    # so make local dns authoritative
    - apt: name=dnsmasq
    - copy:
        dest: /etc/dnsmasq.d/container-dns
        content: |
          # deployed by ansible
          interface=br0
          # log-queries
          log-dhcp
          no-resolv
          # server=8.8.8.8
          # server=192.168.42.1
          server=192.168.43.1
          expand-hosts
          domain=container
          dhcp-range=br0,10.1.1.10,10.1.1.30,4h
          dhcp-host=00:01:04:1b:2C:1A,ethereum,10.1.1.19
          dhcp-host=00:01:04:1b:2C:1B,jessie-test,10.1.1.20
          dhcp-host=00:01:04:1b:2C:1C,ise,10.1.1.21

      notify: restart-dnsmasq

    # IMPORTANT - changes to /etc/resolv.conf, need dnsmasq restart to re-read upstream servers

    # TODO maybe add domain, search?
    - copy:
        dest: /etc/resolv.conf
        content: |
          # deployed by ansible
          # nameserver 127.0.0.1
          nameserver 10.1.1.1

    # http://unix.stackexchange.com/questions/174349/what-overwrites-etc-resolv-conf-on-every-boot
    - copy:
        dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate
        mode: 0777
        content: |
          #!/bin/sh
          # deployed by ansible
          make_resolv_conf() {
              :
          }

    - apt: name=iptables-persistent
    - copy:
        dest: /etc/iptables-rules
        content: |
          # deployed by ansible
          iptables -t filter --flush
          iptables -t nat --flush
          iptables -t mangle --flush

          # natting is handled on the router
          # iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
          # iptables -t nat -A PREROUTING -p tcp --dport 80 -i eth0 -j DNAT --to 10.1.1.16
          # iptables -t nat -A POSTROUTING -s '10.1.1.0/24' -j MASQUERADE

          # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717217
          # TODO - fill in checksums for all udp...
          iptables -t mangle -A POSTROUTING -p udp --dport bootpc -j CHECKSUM --checksum-fill

          # FIXME uggh... had to run interactive and select yes to force overwrite of /etc/iptables/rules.v4 ...
          # dpkg-reconfigure iptables-persistent
      notify: reconfigure-iptables

    #####
    # Support bridge addif for qemu
    # tunctl from uml-utilities only needed for permissions, not strictly needed
    - apt: name=uml-utilities
    - copy:
        dest: /etc/qemu-ifup
        mode: 0755
        content: |
          #!/bin/sh -x
          # deployed by ansible
          echo "i am $(whoami)"
          switch=br0
          if [ -n "$1" ];then
              # has to be run as root...
              # tunctl -u `whoami` -t $1
              ip link set $1 up
              sleep 0.5s
              brctl addif $switch $1
              exit 0
          else
              ECHO "Error: no interface specified"
              exit 1
          fi

    - copy:
        dest: /etc/qemu-ifdown
        mode: 0755
        content: |
          #!/bin/sh -x
          # deployed by ansible
          switch=br0
          if [ -n "$1" ];then
              # permissions...
              brctl delif $switch $1
              ip link delete $1
              exit 0
          else
              echo "Error: no interface specified"
              exit 1
          fi

    #####
    - apt: name=dnsutils
    - apt: name=ethtool
    - apt: name=ffmpeg
    - apt: name=a2ps

    # local changes not in dotfiles for .bashrc
    - blockinfile:
        dest: /home/meteo/.bash_aliases
        insertafter: EOF
        content: |
          # ansible test

    - copy:
        dest: /etc/udev/rules.d/80-ttyusb.rules
        content: |
          # deployed by ansible!
          # ftdi device
          KERNEL=="ttyUSB0", MODE="0666"

    - apt: name=samba
    - copy:
        dest: /etc/samba/smb.conf
        content: |
          # deployed by ansible!
          [global]
          workgroup = WORKGROUP
          dns proxy = no

          interfaces = 10.1.1.0/24 br0
          bind interfaces only = yes

          log file = /var/log/samba/log.%m
          max log size = 1000
          syslog = 0
          panic action = /usr/share/samba/panic-action %d

          server role = standalone server
          passdb backend = tdbsam
          obey pam restrictions = yes
          unix password sync = no
          map to guest = bad user
          usershare allow guests = no

          [meteo]
          path = /home/meteo/Pictures
          valid users = meteo
          read only = yes
      notify: restart-samba


  handlers:
    - include: ../roles/common/handlers/main.yml

    - name: restart-samba
      # command: service samba restart # samba doesn't play nice with systemd
      command: /etc/init.d/samba restart

