
- hosts: drupal
  vars_files:
    - ../vars/jessie.yml
    - ../vars/credentials.yml
  vars:
    - users:
      - { name: meteo,    group: adm, pubkey: "{{meteo_pubkey}}" }
  roles:
    - debian
    - timezone
    - locale
    - common
    - meteo-dotfiles
  tasks:
    - apt: name=mysql-server
