
- hosts: drupal
  vars_files:
    - credentials.yml
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
    - users:
      - { name: meteo,    group: adm, pubkey: "{{meteo_pubkey}}" }
  roles:
    - debian
    - timezone
    - locale
    - common
    - meteo-dotfiles
  tasks:
    - apt: name=mysql-server
