
- hosts: ethereum
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: | 
        ../roles/distribution/tasks/main.yml template=debian.j2 version=jessie upgrade=safe 
        mirror="http://mirror.aarnet.edu.au/debian" 

    - file: path=/root state=directory mode=0755

    - include: ../roles/common/tasks/basic.yml

#    - include: ../roles/ethereum/tasks/cpp-ethereum.yml
#    - include: ../roles/ethereum/tasks/go-ethereum.yml

    - include: ../roles/common/tasks/node.yml

    - include: ../roles/ethereum/tasks/dapple.yml
    - include: ../roles/ethereum/tasks/vim-solidity.yml

  handlers:
    - include: ../roles/common/handlers/main.yml

