
- hosts: all
  roles:
    - yaegashi.blockinfile
  vars:
    - sshkey: "{{ lookup('file', '../resources/keys') }}"
  tasks:
    # - include: | 
    #    ../roles/distribution/tasks/main.yml template=debian.j2 
    #    version=testing upgrade=safe mirror="http://mirror.aarnet.edu.au/debian" 

    # - include: ../roles/common/tasks/basic.yml


    - apt: name=scons
    - apt: name=g++
    - git: repo=https://github.com/mmoss/cryptopp dest=cryptopp version=2772f7b
    - shell: scons --shared --prefix=/usr/local chdir=cryptopp creates=target


    - shell: creates=cmake-3.4.0 {{item}}
      with_items:
        - curl -O https://cmake.org/files/v3.4/cmake-3.4.0.tar.gz 
        - tar -C ~/ -xzf cmake-3.4.0.tar.gz 

    - shell: creates=/usr/local/bin/cmake chdir=cmake-3.4.0 {{item}}
      with_items:
        - ./configure --prefix=/usr/local
        - make 
        - make install




  handlers:
    - include: ../roles/common/handlers/main.yml

