
- hosts: all
  roles:
    - yaegashi.blockinfile
  vars:
    - sshkey: "{{ lookup('file', '../resources/keys') }}"
  tasks:
    - include: |
        ../roles/distribution/tasks/main.yml template=debian.j2
        version=testing upgrade=safe mirror="http://mirror.aarnet.edu.au/debian"

    # - include: ../roles/common/tasks/basic.yml
    - apt: name=vim

    # cryptopp
    - apt: name=git
    - apt: name=scons
    - apt: name=g++
    - git: repo=https://github.com/mmoss/cryptopp dest=cryptopp version=2772f7b
    - shell: scons --shared --prefix=/usr/local chdir=cryptopp creates=target


    # cmake
    - apt: name=make
    - get_url: url=https://cmake.org/files/v3.4/cmake-3.4.0.tar.gz dest=./cmake-3.4.0.tar.gz 
    - unarchive: src=/root/cmake-3.4.0.tar.gz dest=/root copy=no
    - shell: creates=/usr/local/bin/cmake chdir=cmake-3.4.0 {{item}}
      with_items:
        - ./configure --prefix=/usr/local
        - make
        - make install


    # libjson-rpc-cpp
    - apt: name=libjsoncpp-dev
    - apt: name=libargtable2-dev
    - apt: name=libcurl3-dev  
    - apt: name=libmicrohttpd-dev
    - git: repo=https://github.com/cinemast/libjson-rpc-cpp dest=libjson-rpc-cpp version="tags/v0.6.0"
    # will download catch.hpp during cmake and make
    - shell: creates=/usr/local/lib/libjsonrpccpp-client.so chdir=libjson-rpc-cpp {{item}}
      with_items:
        - rm -rf build 
        - mkdir build
        - cd build && cmake .. && make install
        - ldconfig




  handlers:
    - include: ../roles/common/handlers/main.yml

