
- hosts: geonetwork2
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}" }
  vars_files:
    - credentials.yml
  roles:
    - debian
    - timezone
    - locale
    - common
    - meteo-dotfiles
    - tomcat-port-forwarding
    - postgres
    - geonetwork
  tasks:
    - include: ../roles/geonetwork/tasks/restore-db.yml

