
- hosts: geonetwork2
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
  vars_files:
    - credentials.yml
  roles:
    - debian
    - timezone
    - locale
    - meteo
    - tomcat-port-forwarding
    - postgres
    - geonetwork
  tasks:
    - include: ../roles/geonetwork/tasks/restore-db.yml


#- hosts: geonetwork2
#  roles:
#    - yaegashi.blockinfile
#    - tomcat-port-forwarding

#    - include: ../roles/common/tasks/meteo.yml
#    - include: ../roles/postgres/tasks/main.yml
#    # - include: ../roles/geonetwork/tasks/drop-db.yml
#    - include: ../roles/geonetwork/tasks/restore-db.yml
#    - include: ../roles/geonetwork/tasks/main.yml

#  handlers:
#    - include: ../roles/common/handlers/main.yml

