
- hosts: geonetwork2.localnet
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}" }
  vars_files:
    - ../vars/credentials.yml
  roles:
    - jessie
    - update
    - timezone
    - locale
    - common
    - dotfiles
    - tomcat-port-forward
    - postgres
    - geonetwork

  tasks:
    # should always do this, since it's necessary to start from scratch,
    - include: ../roles/geonetwork/tasks/fresh-db.yml

    # - include: ../roles/geonetwork/tasks/restore-db.yml

