
# TODO - expose locale,
#  test runup from scratch

- hosts: geoserver
  vars:
    - user: meteo
    - timezone: Australia/Hobart
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
  vars_files:
    - credentials.yml
  roles:
    - debian
    - timezone
    - basic
    - tomcat-port-forwarding
    - geoserver

