
# TODO - expose locale, expose ssh keys
#  test runup from scratch

- hosts: geoserver
  vars:
    - user: meteo
    - timezone: Australia/Hobart
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - geoserver:
        jndi:
          url: |
            jdbc:postgresql://db-2-aws-syd.aodn.org.au:5432/harvest?\
            loginTimeout=1000&amp;\
            ssl=true&amp;\
            sslfactory=org.postgresql.ssl.NonValidatingFactory\
          username: x 
          password: x 

  roles:
    - debian
    - timezone
    - basic
    - geoserver
  
