
# TODO - expose locale,

- hosts: geoserver
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
  vars_files:
    - credentials.yml
  roles:
    - debian
    - timezone
    - meteo
    - tomcat-port-forwarding
    - geoserver

