
- hosts: 
    - portal.localnet
  vars_files:
    - ../vars/credentials.yml
  vars:
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}", home_dir: /home/meteo }
      - { name: root,   group: ,    pubkey: "{{meteo_pubkey}}", home_dir: /root }

    - warpath: "/home/meteo/imos/aodn-portal/target/aodn-portal-4.28.1-production.war" 
    - warname: "portal.war"

  roles:
    - jessie
    - apt-update
    - sshd
    - timezone
    - locale
    - common
    - users
    - dotfiles
    - tomcat-port-forward
    # keep configuration seperate from deployment
    - portal
    - { role: deploy-war, tags: [ 'whoot' ] }

  tasks:
    - include: "../roles/misc/tasks/tomcat-bash-aliases.yml"
    - include: "../roles/misc/tasks/root-bash-aliases.yml"

