
- hosts: portal
  vars_files:
    - jessie.yml
    - credentials.yml
  roles:
    - debian
    - timezone
    - meteo-dotfiles
    - tomcat-port-forward
    - portal

#  tasks:
#    - include: ../roles/portal/tasks/main.yml

#  handlers:
#    - include: ../roles/common/handlers/main.yml


