
- hosts: portal
  tasks:
    - include: |
        ../roles/distribution/tasks/main.yml template=debian.j2 version=testing upgrade=safe
        mirror="http://mirror.aarnet.edu.au/debian"

    - include: ../roles/common/tasks/basic.yml

    - include: ../roles/portal/tasks/main.yml

  handlers:
    - include: ../roles/common/handlers/main.yml


