
- hosts: portal
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: >
        ../roles/distribution/tasks/main.yml
        mirror=http://mirror.aarnet.edu.au/debian
        template=debian.j2 
        version=jessie 
        upgrade=safe 

    - include: ../roles/common/tasks/basic.yml

    - include: ../roles/portal/tasks/main.yml

  handlers:
    - include: ../roles/common/handlers/main.yml


