
- hosts: rev-proxy
  vars:
    - mirror: http://mirror.internode.on.net/pub/debian
    - version: jessie
    - upgrade: safe
    - timezone: Australia/Hobart
    - locale: en_AU.UTF-8
    - users:
      - { name: meteo, group: adm, pubkey: "{{meteo_pubkey}}" }
  vars_files:
    - credentials.yml
  roles:
    - debian
    - timezone
    - locale
    - common
    - meteo-dotfiles
  tasks:
    # apache
    - apt: name=apache2

    # mod proxy
    - apt: name=libapache2-mod-proxy-html

    # TODO not idempotent
    # enable proxy
    - command: a2enmod proxy proxy_http
    - command: a2enmod proxy proxy_html

    # TODO ordering,
    # disable default site
    - command: a2dissite 000-default.conf

    # TODO control docroot with var
    # tmp dir for files
    - file: path=/var/www/html     state=directory mode=0755
    - file: path=/var/www/html/tmp state=directory mode=0755

    # document root
    - copy:
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
            <body>
              <h1>Woot!!</h1>
              <ul>
                <li><a href="/tmp">tmp</a></li>
                <li><a href="/aatams">aatams</a></li>
                <li><a href="/geoserver">geoserver</a></li>
                <li><a href="/geonetwork">geonetwork</a></li>
                <li><a href="/portal">portal</a></li>
              </ul>
            </body>
          </html>

    # TODO authentification...

    # reverse proxy
    - blockinfile:
        dest: /etc/apache2/sites-available/default.conf
        create: true
        content: |
          <VirtualHost *:80>

            DocumentRoot      /var/www/html

            # Require all granted
            ProxyPass         /aatams http://aatams:8080/aatams
            ProxyPassReverse  /aatams http://aatams:8080/aatams

            ProxyPass         /portal http://portal:8080/portal
            ProxyPassReverse  /portal http://portal:8080/portal

            ProxyPass         /geonetwork http://geonetwork2:8080/geonetwork
            ProxyPassReverse  /geonetwork http://geonetwork2:8080/geonetwork

            ProxyPass         /geoserver http://geoserver:8080/geoserver
            ProxyPassReverse  /geoserver http://geoserver:8080/geoserver

            # Rewriting URLs in hyperlinks
            # ProxyHTMLEnable On
            # ProxyHTMLExtended On
            # ProxyHTMLURLMap http://apache/geonetwork2  /geonetwork
          </VirtualHost>
      notify: reload-apache2

    # enable
    - command: a2ensite default

  handlers:
    - name: reload-apache2
      command: service apache2 reload

