
- hosts: geoserver

  tasks:
    # ok, use shell commands because the point here is not to be idempotent...

    - set_fact: tomcat7=/var/lib/tomcat7
    - set_fact: webapps={{tomcat7}}/webapps
    - set_fact: logs={{tomcat7}}/logs

    - shell: "{{item}}"
      with_items:
        - systemctl stop tomcat7
        - rm {{webapps}}/geoserver.war || true
        - rm -rf {{webapps}}/geoserver || true
        - echo > {{logs}}/catalina.out 

    - copy:
        dest={{webapps}}/geoserver.war
        src=/home/meteo/imos/geoserver/src/web/app/target/geoserver.war

    - shell: "{{item}}"
      with_items:
        - systemctl start tomcat7


