
  # war deployment not handled here,

  - apt: name=tomcat7 update_cache=yes

  - template: src=context.j2 dest=/var/lib/tomcat7/conf/context.xml owner=tomcat7 group=tomcat7
    notify: restart-tomcat7

  - template: src=Portal.groovy.j2 dest=/var/lib/tomcat7/conf/Portal.groovy owner=tomcat7 group=tomcat7
    notify: restart-tomcat7



