
    # - java?
    # postgres?

    # - include: tasks/oracle-java.yml

    - apt: name=tomcat7 update_cache=yes

    # - template: src=context.j2 dest=/etc/tomcat7/context.xml
    # - template: src=context.j2 dest=/etc/tomcat7/context.xml

    - template: src=context.j2 dest=/etc/tomcat7/context.xml
    - template: src=tomcat7.j2 dest=/etc/default/tomcat7

    - file: path=/var/lib/tomcat7/lib/ state=directory
  
    - copy: src=postgresql-9.1-901.jdbc4.jar dest=/var/lib/tomcat7/lib/
    - copy: src=postgis-jdbc-1.3.3.jar       dest=/var/lib/tomcat7/lib/

    # should postgis be here,?  
    - apt: name=postgresql-9.4-postgis-2.1
    - template: src=db.j2 dest=/tmp/db.sql
    - command: sudo -u postgres psql -d postgres -f /tmp/db.sql 

    - file: path=/var/lib/tomcat7/overrides/ state=directory
    - template: src=config-overrides.j2 dest=/var/lib/tomcat7/overrides/config-overrides.xml

    - template: src=log4j-overrides.j2 dest=/var/lib/tomcat7/overrides/log4j-overrides.xml
   
    # TODO permissions - make sure tomcat owns everything-  

    # made geonetwork_data directory
