
# perhaps change name of basic to meteo, since this is highly-specific user environment

#  - set_fact: user=meteo

  - apt: name=sudo

  - lineinfile: >
      dest=/etc/sudoers
      validate='visudo -cf %s'
      state=present
      insertafter=EOF
      "line=%adm ALL=(ALL) NOPASSWD: ALL"

  - user: > 
      name={{user}} 
      shell=/bin/bash 
      groups=adm 
      append=yes

  # - authorized_key: user={{user}} key="{{ lookup('file', '../resources/keys') }}" #"
  - authorized_key: user={{user}} key="{{key}}"

    ###########################

    # Ok, issue is that the deploy templates for timezone are not available
    # options are to specify the full file path directly
    # or separate it into a separate role to be included...

    ###########################3


  - apt: name=locales
  - locale_gen: name=en_AU.UTF-8 state=present

  - apt: name=vim
  - apt: name=screen
  - apt: name=mlocate
  - apt: name=unzip       # for wars
  - apt: name=less

  - apt: name=git

  - git: >
      repo=http://github.com/julian1/dotfiles.git
      dest=/home/{{user}}/dotfiles
      version=master
      force=yes
    sudo: true
    sudo_user: "{{user}}"

  - shell: ./install.sh 2> installed.txt
    sudo: true
    sudo_user: "{{user}}"
    args:
      chdir: /home/{{user}}/dotfiles/
      creates: installed.txt

  - name: Disable shell bell
    replace: dest=/etc/inputrc backup=true regexp='#.*(set bell-style visible.*)' replace='\1'



