# TODO hide the passphrase
# issues are - no public dns update, open ssh port, open dnsmasq port
# printer would have to be on same eth. But maybe not if we bridged it?
# ntp time
# use interface eth1, 172.16.210.254 to provision

- hosts: all
  roles:
     - yaegashi.blockinfile
  tasks:
    - hostname: name=apu

    # change name of sources to update?
    - include: tasks/sources.yml template_src=debian-sources.j2 version=jessie upgrade_type=safe mirror="http://mirror.aarnet.edu.au/debian"
    - include: tasks/sudoers.yml
    - include: tasks/user.yml user=meteo
    # important - we should put the key locally.
    - authorized_key: user=meteo key="{{ lookup('file', '/home/meteo/.ssh/id_rsa.pub') }}" # "

    - apt: name=vim

    - apt: name=ntp

    - apt: name=fail2ban

    # iwconfig - useful to check wlan0 state
    - apt: name=wireless-tools

    # may just have needed a network restart
    # reboot and Atheros AR9280 and wlan0 is seen and can do iwlist scan
    # nope ap worked first time
    - apt: name=firmware-realtek

    # ip forwarding
    - lineinfile: dest=/etc/sysctl.conf backup=true state=present regexp='.*net.ipv4.ip_forward.*' line='net.ipv4.ip_forward = 1'
      notify: reload-sysctl

    - apt: name=hostapd

    # put hostapd first because the file is referred to
    - blockinfile:
        dest: /etc/hostapd/hostapd.conf
        create: true
        content: |
          interface=wlan0
          ssid=My_AP3
          hw_mode=g
          channel=7
          auth_algs=1
          wmm_enabled=0
          # The following gives us wpa2
          macaddr_acl=0
          ignore_broadcast_ssid=0
          wpa=2
          # TODO hide this!!!
          wpa_passphrase=____apple____
          wpa_key_mgmt=WPA-PSK
          wpa_pairwise=TKIP
          rsn_pairwise=CCMP
      notify: restart-hostapd

      # problem for first run, is that we want a clear network interfaces
      # but we need the network up to be able to run ansible

    - blockinfile:
        dest: /etc/network/interfaces
        backup: yes
        content: |
          # loopback
          auto lo
          iface lo inet loopback

          # wan
          allow-hotplug eth0
          iface eth0 inet dhcp
  
          # static
          auto eth1
          iface eth1 inet static
            address 172.16.210.254
            netmask 255.255.255.0

          # lan
          auto eth2
          iface eth2 inet static
            address 192.168.43.1
            netmask 255.255.255.0
            post-up iptables -t nat -A POSTROUTING -s 192.168.43.0/24 ! -d 192.168.43.0/24  -j MASQUERADE
            post-down iptables -t nat -D POSTROUTING -s 192.168.43.0/24 ! -d 192.168.43.0/24  -j MASQUERADE
    
          # wireless lan
          auto wlan0
          iface wlan0 inet static
            hostapd /etc/hostapd/hostapd.conf
            address 192.168.42.1
            netmask 255.255.255.0
            post-up iptables -t nat -A POSTROUTING -s 192.168.42.0/24 ! -d 192.168.42.0/24  -j MASQUERADE
            post-down iptables -t nat -D POSTROUTING -s 192.168.42.0/24 ! -d 192.168.42.0/24  -j MASQUERADE

      notify: 
        # will these all be run together
        - restart-eth0
        - restart-eth1
        - restart-eth2
        - restart-wlan0

    - apt: name=dnsmasq
    - blockinfile:
        dest: /etc/dnsmasq.d/wifi
        create: true
        content: |
          interface=wlan0
          dhcp-range=192.168.42.10,192.168.42.20,255.255.255.0,12h
          dhcp-ignore-names
          log-queries
          log-dhcp
      notify: restart-dnsmasq

    - blockinfile:
        dest: /etc/dnsmasq.d/lan
        create: true
        content: |
          interface=eth2
          dhcp-range=192.168.43.10,192.168.43.20,255.255.255.0,12h
          dhcp-ignore-names
          log-queries
          log-dhcp
      notify: restart-dnsmasq


      # may need to restart wlan0 here? at least when install dnsmasq


  handlers:
    - include: handlers/main.yml




