# container instance, using dhcp
# TODO change name to geonetwork

- hosts: all

  roles:
    - geonetwork

  tasks:
#    - include: tasks/sources.yml template_src=debian-sources.j2 version=jessie upgrade_type=safe mirror="http://mirror.aarnet.edu.au/debian"
#    - include: tasks/sudoers.yml
#    - include: tasks/user.yml user=meteo
#    - authorized_key: user=meteo key="{{ lookup('file', '/home/meteo/.ssh/id_rsa.pub') }}" # "
#    - include: tasks/devenv.yml


    - apt: name=postgresql-9.4-postgis-2.1

    - include: tasks/oracle-java.yml

    - apt: name=tomcat7  update_cache=yes

    - template: src=geonetwork/templates/context.j2 dest=/etc/tomcat7/context.xml
    - template: src=geonetwork/templates/tomcat7.j2 dest=/etc/default/tomcat7

    - file: path=/var/lib/tomcat7/lib/ state=directory
  
    # TODO must be a better way to drill down 
    - copy: src=geonetwork/files/postgresql-9.1-901.jdbc4.jar dest=/var/lib/tomcat7/lib/
    - copy: src=geonetwork/files/postgis-jdbc-1.3.3.jar       dest=/var/lib/tomcat7/lib/


