
  # use unarchive to pull war, defined in credentials from jenkins?
  # see -> grails-1.3.7.yml as example
  # the war shouldn't be in credentials...

  # this is really generic, and should be factored out

  - copy: src={{aatams.war}} dest={{webapps}}/aatams.war
    register: deployed

  - shell: "{{item}}"
    with_items:
      - systemctl stop tomcat7
      - rm -rf {{webapps}}/aatams || true
      - echo > {{logs}}/catalina.out
    when: deployed.changed == true
    notify: restart-tomcat7

