
    - apt: name=tomcat7 update_cache=yes

    # jdbc drivers
    - file: path=/var/lib/tomcat7/lib/ state=directory owner=tomcat7

    - copy: src=postgresql-9.1-901.jdbc4.jar dest=/var/lib/tomcat7/lib/ owner=tomcat7


    # jndi
    - template: src=context.j2 dest=/etc/tomcat7/context.xml owner=tomcat7
      notify: restart-tomcat7

    # tomcat opts
    - template: src=tomcat7.j2 dest=/etc/default/tomcat7 owner=tomcat7
      notify: restart-tomcat7


    # data directory
    - file: path=/var/lib/tomcat7/aatams_data state=directory owner=tomcat7

    - template: src=aatams.groovy.j2 dest=/var/lib/tomcat7/aatams_data/aatams.groovy owner=tomcat7
      notify: restart-tomcat7

    # war
    # TODO owner?
    - get_url: url=https://jenkins.aodn.org.au/job/aatams_prod/lastSuccessfulBuild/artifact/target/aatams-3.15.0.war 
        dest=/var/lib/tomcat7/webapps/aatams.war
      notify: restart-tomcat7


    # check for database
    - shell: psql -tAc "select 1 from pg_database where datname='aatams'"
      become: yes
      become_user: postgres
      register: have_aatams_db
      changed_when: false


    # tomcat must be stopped - alternatively kill the db connections
    - name: Fresh Geonetwork Database
      shell: "{{item}}"
      become: yes
      become_user: postgres
      with_items:
        - |
          psql -d postgres -c "
            drop user if exists aatams;
            create user aatams unencrypted password 'aatams';
            "
        - psql -d postgres -c "create database aatams owner aatams"
        - | 
          psql -d aatams -c "
            create extension postgis;
            create schema aatams authorization aatams;
            alter database aatams set search_path to 'aatams','public';
            "
      when: have_aatams_db.stdout != "1"




