
  # Bridge with dhcp and dns configured

  # may need to restart networking
  # - command: systemctl restart networking

  - apt: name=bridge-utils
  - blockinfile:
      dest: /etc/network/interfaces
      backup: yes
      content: |
        auto br0
        # whoot  whoot whoot whoot whoot
        iface br0 inet static
          address 10.1.1.1
          netmask 255.255.255.0
          bridge_ports dummy0
          bridge_stp off
          bridge_fd 0
          post-up echo 1 > /proc/sys/net/ipv4/ip_forward
          # Simplify syntax and use the -o interface flag?
          post-up   iptables -t nat -A POSTROUTING -s '10.1.1.0/24' -j MASQUERADE
          post-down iptables -t nat -D POSTROUTING -s '10.1.1.0/24' -j MASQUERADE
          post-up   iptables -t mangle -A POSTROUTING -p udp --dport bootpc -j CHECKSUM --checksum-fill
          post-down iptables -t mangle -D POSTROUTING -p udp --dport bootpc -j CHECKSUM --checksum-fill

    notify: restart-br0

  - apt: name=dnsmasq
  - blockinfile:
      dest: /etc/dnsmasq.d/container-dns
      create: true
      content: |
        # the interface
        interface=br0
        # Set up your local domain here
        # domain=julian.home
        # goes to /var/log/syslog
        log-queries
        log-dhcp
        # range for leases
        dhcp-range=br0,10.1.1.10,10.1.1.20,4h
        # entries
        dhcp-host=00:01:04:1b:2C:1A,ethereum,10.1.1.19

    notify: restart-dnsmasq

  # Just getting dhcpclient to add the extra dns is a lot simpler than installing resolvconf 
  # add to bridge
  - lineinfile: dest=/etc/dhcp/dhclient.conf backup=true state=present insertafter='#prepend' line='prepend domain-name-servers 10.1.1.1;'


  # we don't want this anymore 
  # prevent from being overwritten by host dhcp
  # TODO don't think this works
  # - lineinfile: dest=/etc/dhcp/dhclient.conf backup=true state=present backrefs=yes regexp='(.*)domain-name-servers,(.*)' line='\1\2'

  # ip forwarding for nat - debian only?
  - lineinfile: dest=/etc/sysctl.conf backup=true state=present regexp='.*net.ipv4.ip_forward.*' line='net.ipv4.ip_forward = 1'
    notify: reload-sysctl

