

  - shell: "{{item}}"
    args:
      chdir: "{{jdk_deploy_path}}"
      creates: jdk1.7.0_80
    with_items:
      - >
        curl -L -H 'Cookie:oraclelicense=accept-securebackup-cookie'
        http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz
        -o jdk-7u80-linux-x64.tar.gz 
      - tar xf jdk-7u80-linux-x64.tar.gz 

    # handle PATH setup elsewhere
