
  # TODO factor out the hard-coded user directory
  # vimrc requires the appropriate assocation to be set eg, #  au BufNewFile,BufRead *.sol setf solidity


  # .vimrc
  # TODO maybe templatize
  - copy:       src=vimrc dest=/home/meteo/.vimrc


  # vim directories for temp files and pathogen
  # vim tmp file handling
  # http://stackoverflow.com/questions/821902/disabling-swap-files-creation-in-vim
  - file: path="/home/meteo/{{item}}" state=directory owner=meteo group=meteo
    with_items:
      - "/.vim"
      - "/.vim/backup"
      - "/.vim/swap"
      - "/.vim/undo"
      - "/.vim/autoload"
      - "/.vim/bundle"

  # pathogen
  # https://github.com/tpope/vim-pathogen
  - get_url: url='https://tpo.pe/pathogen.vim'                dest=/home/meteo/.vim/autoload/pathogen.vim

  # solidity, sol
  - git: repo=https://github.com/tomlion/vim-solidity         dest=/home/meteo/.vim/bundle/vim-solidity

  # rust, rs
  - git: repo=https://github.com/rust-lang/rust.vim           dest=/home/meteo/.vim/bundle/rust

  # coquille, v
  - git: repo=https://github.com/the-lambda-church/coquille   dest=/home/meteo/.vim/bundle/coquille


