
  - debug: msg="{{ansible_distribution_release}}"

  - apt: name=postgresql-9.4-postgis-2.1
    when: ansible_distribution_release == 'jessie'

  #- apt: name=postgresql-9.4-postgis-2.2   # debian testing

  - set_fact: main=/etc/postgresql/9.4/main

  - copy:
      dest: "{{main}}/postgresql.conf"
      owner: postgres
      content: |
        # deployed by ansible!
        listen_addresses = '*'
        port = 5432
        max_connections = 100
        shared_buffers = '24MB'
        log_line_prefix = '%t %h %u %d %p %e'

        log_statement = all

        datestyle = 'iso, mdy'
        default_text_search_config = 'pg_catalog.english'
        ssl = on
        data_directory = '/var/lib/postgresql/9.4/main'
        hba_file = '{{main}}/pg_hba.conf'

        ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
        ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'

    notify: restart-postgres

  - copy:
      dest: "{{main}}/pg_hba.conf"
      owner: postgres
      content: |
        # deployed by ansible!
        hostssl  all  postgres  0.0.0.0/0  reject
        local    all  postgres  peer
        hostssl  all  all       0.0.0.0/0  md5

    notify: restart-postgres

  - file: path=/ansible state=directory

  - copy:
      src: admin.sql
      dest: /ansible/admin.sql

