

  - set_fact: tomcat7=/var/lib/tomcat7
  - set_fact: webapps={{tomcat7}}/webapps
  - set_fact: logs={{tomcat7}}/logs

  - service: name=tomcat7 state=stopped

  - copy: src={{warpath}} dest={{webapps}}/{{warname}}

  - shell: "{{item}}"
    with_items:
      - echo > {{logs}}/catalina.out


  - command: md5sum {{webapps}}/{{warname}}
    register: result
    ignore_errors: True

  - debug: msg="war md5sum: {{result.stdout}}" #"


  - service: name=tomcat7 state=started

