
  # eg. ansible-playbook ./plays/deploy-war.yml -i n.n.n.n, --extra-vars "warpath=~/imos/geoserver-1.0.0-imos.war warname=geoserver.war"

  - set_fact: tomcat7=/var/lib/tomcat7
  - set_fact: webapps={{tomcat7}}/webapps
  - set_fact: logs={{tomcat7}}/logs

  # - set_fact: conf={{tomcat7}}/conf
  # - set_fact: lib={{tomcat7}}/lib

  - service: name=tomcat7 state=stopped

  - copy: src={{warpath}} dest={{webapps}}/{{warname}}

  # TODO, delete existing exploded war?.

  - shell: "{{item}}"
    with_items:
      - echo > {{logs}}/catalina.out


  - command: md5sum {{webapps}}/{{warname}}
    register: result
    ignore_errors: True

  - debug: msg="{{result.stdout}}" #"


  - service: name=tomcat7 state=started

